#!/bin/sh
set -eu
fail() { echo "FAIL: $*" >&2; exit 1; }

root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$root"

grep -q '@app.get("/api/network/wifi/scan")' src/equip1d/api.py || fail "daemon must expose Wi-Fi scan API"
grep -q '@app.post("/api/network/wifi")' src/equip1d/api.py || fail "daemon must expose Wi-Fi setup API"
grep -q '@app.post("/api/network/ap")' src/equip1d/api.py || fail "daemon must expose AP fallback API"
grep -q 'class WifiManager' src/equip1d/wifi.py || fail "daemon must include Wi-Fi manager"
grep -q 'ap-force' src/equip1d/wifi.py || fail "Wi-Fi scan should support AP-mode scan"
grep -q 'env\["EQUIP1_WIFI_MODE"\] = wifi_mode' src/equip1d/wifi.py || fail "network restart must override stale daemon Wi-Fi mode env"
grep -q 'os.environ\["EQUIP1_WIFI_MODE"\] = "client"' src/equip1d/wifi.py || fail "daemon runtime Wi-Fi mode env must update after client join"
grep -q 'os.environ\["EQUIP1_WIFI_CLIENT_SSID"\] = clean_ssid' src/equip1d/wifi.py || fail "daemon runtime client SSID env must update after client join"
grep -q 'EQUIP1_OLED_NETWORK_PROMPT' src/equip1d/wifi.py || fail "Wi-Fi join must request OLED Network screen"
grep -q 'wifi_mode = ap' src/buildroot/overlay/etc/equip1/equip-1.ini || fail "default network mode must remain AP/skippable"
grep -q 'port = 80' src/buildroot/overlay/etc/equip1/equip-1.ini || fail "production dashboard must default to port 80"
grep -q 'client_fallback_ap = true' src/buildroot/overlay/etc/equip1/equip-1.ini || fail "client Wi-Fi must fall back to AP by default"
grep -q 'Falling back to Equip-1 AP mode' src/buildroot/overlay/etc/init.d/S50network || fail "network init must fall back to AP on client failure"
grep -q 'ip addr flush dev "$AP_IFACE"' src/buildroot/overlay/etc/init.d/S50network || fail "client Wi-Fi startup must clear stale AP address"
grep -q 'EQUIP1_PORT network port 80' src/buildroot/overlay/etc/init.d/S60equip1d || fail "daemon init must default to HTTP port 80"
grep -q 'http://$AP_IP/' src/buildroot/overlay/etc/init.d/S50network || fail "AP mode must report IP URL without a port"
grep -q '_http_url(ap_ip, port)' src/equip1d/network.py || fail "AP network state must use IP URL"
grep -q '_http_url(lan_ip, port)' src/equip1d/network.py || fail "LAN network state must use IP URL"
grep -q 'BR2_TARGET_GENERIC_HOSTNAME="equip-1"' src/buildroot/configs/equip1_defconfig || fail "Rock hostname must remain equip-1"
grep -q '<span>Network</span>' src/uis/web/pages/index.vue || fail "System section must include a Network row"
! grep -q 'card-title">Network' src/uis/web/pages/index.vue || fail "Network must be integrated into System, not a separate card"
grep -q '<span>Network</span>' src/uis/web/pages/index.vue || fail "System section must include network controls"
grep -q '"Join"' src/uis/web/pages/index.vue || fail "web UI must include one-word Wi-Fi join control"
grep -q 'Fetching.*Update' src/uis/web/pages/index.vue || fail "Network section must include update fetching label"
grep -q 'isAccessPointNetwork ? "Network" : "AP mode"' src/uis/web/pages/index.vue || fail "Network mode button must switch between Network and AP mode"
grep -q 'Switch back to AP mode?' src/uis/web/pages/index.vue || fail "AP mode switch must ask for confirmation"
grep -q '>Close<' src/uis/web/pages/index.vue || fail "Wi-Fi setup form must have a Close button"
grep -q "mode: 'client'" src/uis/web/composables/useEquip1State.ts || fail "mock UI must simulate connected Wi-Fi state by default"
grep -q 'Switched to AP mode' src/uis/web/pages/index.vue || fail "mock UI must simulate AP switching"
grep -q 'networkIp' src/uis/web/pages/index.vue || fail "web UI must derive update availability from actual network IP"
grep -q "model: 'ROCK 2F'" src/uis/web/composables/useEquip1State.ts || fail "mock system model should be concise"
grep -q '<select v-model="wifiSsid" class="text-input filename-label"' src/uis/web/pages/index.vue || fail "SSID must be a dropdown with filename text input styling"
grep -q 'text-input filename-label' src/uis/web/pages/index.vue || fail "Network inputs must use filename text input styling"
grep -q 'Connect Equip-1 to Wi-Fi for updates\.' src/uis/web/pages/index.vue || fail "updater must explain Wi-Fi requirement"
grep -q 'connectedWifiSsid' src/uis/web/pages/index.vue || fail "web UI must show connected SSID in network state"
grep -q 'return truncateSsid(state.value?.network?.ssid)' src/uis/web/pages/index.vue || fail "web UI must truncate long SSIDs only in connected network state"
! grep -q '{{ truncateSsid(ssid) }}' src/uis/web/pages/index.vue || fail "SSID dropdown must keep full SSID labels"
grep -q 'showNativeMessage(message)' src/uis/web/pages/index.vue || fail "Wi-Fi join message must use native browser prompt"
grep -q 'v-if="!wifiSwitchPending" class="actions two system-actions"' src/uis/web/pages/index.vue || fail "Join/update buttons must hide while Wi-Fi switch is pending"

sh -n src/buildroot/overlay/etc/init.d/S50network
grep -q 'current_screen_idx = 1' src/uis/oled/app.py || fail "OLED must jump to Network screen after Wi-Fi joins"
grep -q 'qr_mode = "url"' src/uis/oled/app.py || fail "OLED must open Network screen directly in URL QR mode"
grep -q 'mode in {"access_point", "ap"}' src/uis/oled/screens.py || fail "OLED AP QR must only be available in AP mode"
grep -q 'self.qr_mode == "wifi" and mode in {"access_point", "ap"}' src/uis/oled/screens.py || fail "OLED must not render stale AP QR outside AP mode"
python3 -m compileall -q src/equip1d src/uis/oled

echo "ok - Wi-Fi setup and updater networking are wired"
